/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Faceted catalog listing. Filters are AND-combined across keys and
         *     OR-combined within a key, which is the behaviour a facet panel implies:
         *     ticking two brands widens, ticking a brand and a kind narrows.
         *
         *     `brand` + `model` together are how a shopper finds the consumable that
         *     fits their printer — the single most important query this shop serves.
         *     They filter on the `compatibility` of the product, not on its own
         *     manufacturer; see `Compatibility`.
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Printer manufacturers this catalog carries consumables for. Small and
         *     near-static, so the storefront caches it hard and renders the finder
         *     without a round trip.
         */
        get: operations["listPrinterBrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compat/brands/{brand}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Printer models for one brand, for the second step of the finder.
         *     Separate from `/compat/brands` so the payload stays small: shipping every
         *     model of every brand up front would be a large download to support one
         *     dropdown.
         */
        get: operations["listPrinterModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Static product content only. Cacheable with a long TTL. Deliberately
         *     excludes price and availability so the PDP can cache this shell and
         *     stream the volatile parts separately.
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Price and availability. Volatile: short TTL or uncached. Split from
         *     product content so a cached PDP shell can never serve a stale price.
         */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Live prices and availability for several products at once.
         *
         *     Exists so a listing page can show prices without giving up its cache.
         *     The product grid is cached for hours; offers must never be. Fetching
         *     them per card would mean one uncached round trip per product, so the
         *     storefront issues exactly one batched call per listing page and streams
         *     the result into the already-rendered grid behind `<Suspense>`.
         *
         *     Unknown slugs are omitted rather than erroring: a product deleted
         *     between the cached listing and this call is an ordinary race, and it
         *     must not blank the prices of every other product on the page.
         */
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addCartLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeCartLine"];
        options?: never;
        head?: never;
        /**
         * @description Sets an absolute quantity, never a delta. The client debounces and
         *     coalesces rapid changes, so a delta API would produce racing writes.
         */
        patch: operations["updateCartLine"];
        trace?: never;
    };
    "/carts/{cartId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Merges the guest cart into the authenticated user's cart on login.
         *     Backend-owned so every client behaves identically: sum quantities per
         *     variant, re-validate stock, clamp to available.
         */
        post: operations["mergeCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates the payment intent and returns the PSP redirect URL. The
         *     idempotency key is derived from cart id + cart version, so a
         *     double-clicked Pay button cannot create two orders.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Authoritative order state. The storefront calls this on return from the
         *     PSP; return-URL query parameters are attacker-controlled and are never
         *     trusted.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Integer minor units (e.g. 1099 == EUR 10.99) plus an ISO 4217 code.
         *     Never a float: binary floating point cannot represent decimal currency
         *     exactly, and the rounding error lands on a customer's invoice.
         */
        Money: {
            amountMinor: number;
            currency: string;
        };
        /** @description Dimensions are required so the UI can reserve space and avoid CLS. */
        Image: {
            /** Format: uri */
            url: string;
            alt: string;
            width: number;
            height: number;
        };
        /**
         * @description What the consumable physically is. Drives category navigation and is a
         *     facet. `other` exists so an unrecognised backend value degrades to a
         *     listable product rather than breaking the catalog.
         * @enum {string}
         */
        ProductKind: "toner" | "inkjet" | "drum" | "fuser" | "waste" | "roller" | "other";
        /**
         * @description `none` for items that have no colour at all (fuser units, rollers, waste
         *     containers) — distinct from an unknown or absent colour.
         * @enum {string}
         */
        ProductColor: "black" | "cyan" | "magenta" | "yellow" | "tricolor" | "none";
        /** @description A printer manufacturer, e.g. Brother, HP, Kyocera. */
        PrinterBrand: {
            /** @description URL-safe identifier */
            slug: string;
            name: string;
            productCount?: number;
        };
        /** @description A printer model within a brand, e.g. HL-2130. */
        PrinterModel: {
            slug: string;
            name: string;
            productCount?: number;
        };
        /**
         * @description One printer brand and the models of it this consumable fits. A product
         *     carries several of these, because a single cartridge typically fits
         *     dozens of models and occasionally more than one brand.
         *
         *     This is the field that makes the shop usable: it is what `brand`/`model`
         *     on `/products` filter against, and what the PDP prints so a buyer can
         *     confirm the part fits before ordering.
         */
        Compatibility: {
            printerBrand: components["schemas"]["PrinterBrand"];
            printerModels: components["schemas"]["PrinterModel"][];
        };
        /**
         * @description Consumable specifications. Every field is optional because the catalog
         *     mixes categories: a fuser unit has no page yield or colour, and a
         *     third-party cartridge may have no OEM code at all.
         */
        ProductAttributes: {
            color?: components["schemas"]["ProductColor"];
            /**
             * @description Rated page yield at the industry standard coverage (ISO/IEC 19752 for
             *     mono toner, 24711 for inkjet). The headline number on every listing —
             *     price per page is how these products are actually compared.
             */
            yieldPages?: number;
            /**
             * @description Original manufacturer part codes this item replaces, e.g.
             *     ["CB435A", "35A"]. Buyers search by these, so they are matched
             *     against and displayed verbatim — never normalised or prettified.
             */
            oemCodes?: string[];
            /** @description Who made this consumable (G&G, INTEGRAL, CET, HYB…). */
            manufacturer?: string;
            /**
             * @description True for genuine OEM stock, false for a compatible equivalent.
             *     Supplied explicitly by the backend and never inferred from the title:
             *     selling a compatible cartridge as original is a consumer-protection
             *     problem, not a display detail.
             */
            isOriginal?: boolean;
        };
        Product: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            kind?: components["schemas"]["ProductKind"];
            attributes?: components["schemas"]["ProductAttributes"];
            compatibility?: components["schemas"]["Compatibility"][];
            images: components["schemas"]["Image"][];
            variants: components["schemas"]["Variant"][];
        };
        Variant: {
            id: string;
            title: string;
        };
        FacetValue: {
            /** @description The value to send back as a query parameter. */
            value: string;
            /**
             * @description Display text, supplied by the backend rather than derived from
             *     `value`. The storefront must not map codes to Romanian prose itself:
             *     that mapping would silently go stale as the catalog grows.
             */
            label: string;
            count: number;
        };
        Facet: {
            /**
             * @description The `/products` query parameter this facet drives.
             * @enum {string}
             */
            key: "brand" | "model" | "kind" | "manufacturer" | "color";
            label: string;
            values: components["schemas"]["FacetValue"][];
        };
        ProductPage: {
            items: components["schemas"]["Product"][];
            /** @description Cursor pagination; offsets duplicate rows under concurrent writes. */
            nextCursor?: string | null;
            /** @description Total matches for the filter, not the size of this page. */
            total?: number;
            /**
             * @description Available refinements for the current filter, with counts computed
             *     against it. Counts are catalog data and must never depend on the
             *     session, or a per-visitor number would land in a shared cache.
             */
            facets?: components["schemas"]["Facet"][];
        };
        Availability: {
            inStock: boolean;
            quantity: number;
        };
        /**
         * @description One quantity break. `unitPrice` is the VAT-inclusive price each unit costs
         *     once `minQuantity` is reached — already computed by the backend, never a
         *     percentage the storefront applies.
         */
        PriceTier: {
            minQuantity: number;
            unitPrice: components["schemas"]["Money"];
            unitPriceExVat?: components["schemas"]["Money"];
        };
        /**
         * @description Price and availability for one variant.
         *
         *     **Both VAT figures are supplied by the backend.** The storefront never
         *     derives one from the other, even though the rate is right there. Applying
         *     a rate means multiplying money by a fraction, which requires a rounding
         *     policy — and `src/lib/money.ts` refuses fractional multipliers precisely
         *     so that policy cannot be invented at the render edge. In Romania the
         *     ex-VAT figure is what B2B buyers compare and what appears on the invoice,
         *     so a storefront-side rounding error is a billing discrepancy, not a
         *     cosmetic one.
         */
        Offer: {
            variantId: string;
            /** @description VAT-inclusive unit price. The headline figure. */
            price: components["schemas"]["Money"];
            /** @description VAT-exclusive unit price, for business buyers. */
            priceExVat: components["schemas"]["Money"];
            /**
             * @description VAT rate in basis points (1900 = 19%). Integer, so the rate itself is
             *     exact. Present for display and invoicing, NOT so the client can
             *     compute the other price.
             */
            vatRate: number;
            compareAtPrice?: components["schemas"]["Money"];
            /**
             * @description Quantity breaks, ascending by `minQuantity`. Display-only in the
             *     storefront: what a customer is charged comes from the cart response,
             *     never from re-applying a tier client-side.
             */
            priceTiers?: components["schemas"]["PriceTier"][];
            availability: components["schemas"]["Availability"];
        };
        /**
         * @description An offer tagged with the slug it belongs to. The pairing is explicit
         *     rather than positional, because the response omits slugs that did not
         *     resolve and an index-based mapping would then silently attach prices to
         *     the wrong products.
         */
        OfferListItem: {
            slug: string;
            offer: components["schemas"]["Offer"];
        };
        CartLine: {
            id: string;
            variantId: string;
            title: string;
            image?: components["schemas"]["Image"];
            quantity: number;
            unitPrice: components["schemas"]["Money"];
            lineTotal: components["schemas"]["Money"];
        };
        CartTotals: {
            subtotal: components["schemas"]["Money"];
            shipping?: components["schemas"]["Money"];
            tax?: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
        };
        Cart: {
            id: string;
            /** @description Increments on every mutation. Used for checkout idempotency. */
            version: number;
            lines: components["schemas"]["CartLine"][];
            totals: components["schemas"]["CartTotals"];
        };
        CheckoutSession: {
            orderRef: string;
            /** Format: uri */
            redirectUrl: string;
        };
        Order: {
            id: string;
            /**
             * @description `pending` is a real state, not an error: the PSP webhook may not have
             *     landed when the customer returns. The storefront polls rather than
             *     guessing an outcome.
             * @enum {string}
             */
            status: "pending" | "paid" | "failed" | "cancelled";
            total: components["schemas"]["Money"];
        };
        Error: {
            /**
             * @description Stable and machine-readable. `message` is for logs and developers;
             *     never branch on it, and never show it to customers.
             * @enum {string}
             */
            code: "not_found" | "out_of_stock" | "price_changed" | "cart_expired" | "unauthorized" | "validation_failed" | "unavailable";
            message: string;
            /**
             * @description Code-specific, machine-readable payload. Because `message` must never
             *     be shown to a customer, anything the UI needs to react to belongs
             *     here.
             *
             *     - `out_of_stock`: `variantId`, `available`
             *     - `price_changed`: `oldPrice`, `newPrice`
             *     - `validation_failed`: `field` (the field path that failed, so the
             *       storefront can mark the right input using its own copy)
             */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Structured error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Deterministic per logical intent, not random per call. Replaying a key
         *     with an identical payload returns the original result; replaying with a
         *     different payload is a 422. Retention: at least 24h.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: {
                category?: string;
                cursor?: string;
                limit?: number;
                /** @description Printer manufacturer the consumable must be compatible with. */
                brand?: string;
                /**
                 * @description Printer model the consumable must be compatible with. Only meaningful
                 *     alongside `brand`: model designations are not unique across brands.
                 */
                model?: string;
                kind?: components["schemas"]["ProductKind"];
                /** @description Who made the consumable (G&G, INTEGRAL, CET…), not the printer brand. */
                manufacturer?: string;
                color?: components["schemas"]["ProductColor"];
                /** @description When true, exclude products with no available stock. */
                inStock?: boolean;
                sort?: "relevance" | "price_asc" | "price_desc" | "yield_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPrinterBrands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Printer brands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PrinterBrand"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPrinterModels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Printer models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PrinterModel"][];
                    };
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listOffers: {
        parameters: {
            query: {
                /** @description Comma-separated product slugs. Capped to protect the backend. */
                slugs: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers for the slugs that resolved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OfferListItem"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCart: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    addCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    variantId: string;
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Stock or price conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
                lineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
                lineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Stock or price conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    mergeCart: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cartId: string;
                    cartVersion: number;
                    /** Format: email */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Cart changed since the version supplied. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
}
