/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Static product content only. Cacheable with a long TTL. Deliberately
         *     excludes price and availability so the PDP can cache this shell and
         *     stream the volatile parts separately.
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Price and availability. Volatile: short TTL or uncached. Split from
         *     product content so a cached PDP shell can never serve a stale price.
         */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addCartLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeCartLine"];
        options?: never;
        head?: never;
        /**
         * @description Sets an absolute quantity, never a delta. The client debounces and
         *     coalesces rapid changes, so a delta API would produce racing writes.
         */
        patch: operations["updateCartLine"];
        trace?: never;
    };
    "/carts/{cartId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Merges the guest cart into the authenticated user's cart on login.
         *     Backend-owned so every client behaves identically: sum quantities per
         *     variant, re-validate stock, clamp to available.
         */
        post: operations["mergeCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates the payment intent and returns the PSP redirect URL. The
         *     idempotency key is derived from cart id + cart version, so a
         *     double-clicked Pay button cannot create two orders.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Authoritative order state. The storefront calls this on return from the
         *     PSP; return-URL query parameters are attacker-controlled and are never
         *     trusted.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Integer minor units (e.g. 1099 == EUR 10.99) plus an ISO 4217 code.
         *     Never a float: binary floating point cannot represent decimal currency
         *     exactly, and the rounding error lands on a customer's invoice.
         */
        Money: {
            amountMinor: number;
            currency: string;
        };
        /** @description Dimensions are required so the UI can reserve space and avoid CLS. */
        Image: {
            /** Format: uri */
            url: string;
            alt: string;
            width: number;
            height: number;
        };
        Product: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            images: components["schemas"]["Image"][];
            variants: components["schemas"]["Variant"][];
        };
        Variant: {
            id: string;
            title: string;
        };
        ProductPage: {
            items: components["schemas"]["Product"][];
            /** @description Cursor pagination; offsets duplicate rows under concurrent writes. */
            nextCursor?: string | null;
        };
        Availability: {
            inStock: boolean;
            quantity: number;
        };
        Offer: {
            variantId: string;
            price: components["schemas"]["Money"];
            compareAtPrice?: components["schemas"]["Money"];
            availability: components["schemas"]["Availability"];
        };
        CartLine: {
            id: string;
            variantId: string;
            title: string;
            image?: components["schemas"]["Image"];
            quantity: number;
            unitPrice: components["schemas"]["Money"];
            lineTotal: components["schemas"]["Money"];
        };
        CartTotals: {
            subtotal: components["schemas"]["Money"];
            shipping?: components["schemas"]["Money"];
            tax?: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
        };
        Cart: {
            id: string;
            /** @description Increments on every mutation. Used for checkout idempotency. */
            version: number;
            lines: components["schemas"]["CartLine"][];
            totals: components["schemas"]["CartTotals"];
        };
        CheckoutSession: {
            orderRef: string;
            /** Format: uri */
            redirectUrl: string;
        };
        Order: {
            id: string;
            /**
             * @description `pending` is a real state, not an error: the PSP webhook may not have
             *     landed when the customer returns. The storefront polls rather than
             *     guessing an outcome.
             * @enum {string}
             */
            status: "pending" | "paid" | "failed" | "cancelled";
            total: components["schemas"]["Money"];
        };
        Error: {
            /**
             * @description Stable and machine-readable. `message` is for logs and developers;
             *     never branch on it, and never show it to customers.
             * @enum {string}
             */
            code: "not_found" | "out_of_stock" | "price_changed" | "cart_expired" | "unauthorized" | "validation_failed" | "unavailable";
            message: string;
            /**
             * @description Code-specific, machine-readable payload. Because `message` must never
             *     be shown to a customer, anything the UI needs to react to belongs
             *     here.
             *
             *     - `out_of_stock`: `variantId`, `available`
             *     - `price_changed`: `oldPrice`, `newPrice`
             *     - `validation_failed`: `field` (the field path that failed, so the
             *       storefront can mark the right input using its own copy)
             */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Structured error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Deterministic per logical intent, not random per call. Replaying a key
         *     with an identical payload returns the original result; replaying with a
         *     different payload is a 422. Retention: at least 24h.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: {
                category?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    createCart: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    addCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    variantId: string;
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Stock or price conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
                lineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCartLine: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
                lineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Updated cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Stock or price conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    mergeCart: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged cart. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Deterministic per logical intent, not random per call. Replaying a key
                 *     with an identical payload returns the original result; replaying with a
                 *     different payload is a 422. Retention: at least 24h.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cartId: string;
                    cartVersion: number;
                    /** Format: email */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Cart changed since the version supplied. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
}
